echo Executing NeXTTool to upload /cygdrive/c/cygwin/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
 /cygdrive/C/cygwin/nexttool/NeXTTool.exe /COM=usb -firmware=/cygdrive/c/cygwin/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
